# Generated by Django 5.1.2 on 2024-11-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0003_alter_interest_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
