# Generated by Django 5.1.2 on 2024-11-04 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='property.property'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='buyer',
            field=models.ManyToManyField(limit_choices_to={'role': 'BUYER'}, through='property.Contract', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
