# Generated by Django 5.1.2 on 2024-11-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_buyer_property_descriprion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='descriprion',
            new_name='description',
        ),
    ]
