# Generated by Django 5.1.2 on 2024-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('BUYER', 'Buyer')], default='BUYER', max_length=5),
        ),
    ]
